[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.session", "php82Extensions.mbstring"]

[phases.build]

[start]
cmd = "php -d extension=mysqli -d extension=pdo_mysql -S 0.0.0.0:$PORT -t ."
